### ISSUE TITLE
Arduino 1.0.5 compatibility

### ISSUE THREAD

**Issue by fpapadopou** [sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library#1]
The current file structure of the library is not supported by Arduino 1.0.5. I would have to move the .cpp and .h files out of the <b>src</b> directory in order to use it with Arduino 1.0.5. Is there any chance that you guys create a 1.0.5 branch in which the .cpp and .h files of the library exist in the root directory? :)
Thanks!

**Comment by nseidle** [comment]
Oh man. We're spending great efforts to get all our libraries to work with the Arduino 1.6.x system (we just created a few hundred new repos). I'm sorry but I don't think we can handle managing a 1.0.x branch across all the products (my people have pitchforks, I'm kidding, no really).

**Comment by ToniCorinne** [comment]
A more satisfying answer for you - 

We did just update all of our libraries to the new 1.6 version. Luckily however, we are on GitHub, which means version control is a thing! If you check out [this commit](https://github.com/sparkfun/HTU21D_Breakout/tree/f9109c2ed1c047b5c921ef37353f9aaca3e23909) on the product repo, the library is 1.0.x compatible there. Just click the download zip on the right hand side and you'll have a copy of the older library.

**Comment by fpapadopou** [comment]
@nseidle @ToniCorinne thanks guys :)
