### ISSUE TITLE
two wire utilization

### ISSUE THREAD

**Issue by ghostdrummer** [sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library#8]
hi, i have an issue with the two wire utilizations, i have an esp32 with arduino IDE, i want know how to use the HTU21D library with the multiple I2C bus of the esp32. thanks

**Comment by nseidle** [comment]
Hi - Using two sensors on two different buses requires a significant change to this library. This library is very old and is not [genericized](https://www.sparkfun.com/news/2194) like it should have been. We no longer produce a board that uses the HTU21D so we won't be updating this library. I recommend our [Si7021](https://www.sparkfun.com/products/13763) or better yet, the [BMP280](https://www.sparkfun.com/products/14348).
